import type {
	WithJustOneMailboxInFromOriginatorFieldsOfHeadersOfMessage,
	WithMoreThanOneMailboxInFromOriginatorFieldsOfHeadersOfMessage,
} from "../implementations/index.ts";
export type SupportedOriginatorFieldsOfHeadersOfMessage =
	| WithJustOneMailboxInFromOriginatorFieldsOfHeadersOfMessage
	| WithMoreThanOneMailboxInFromOriginatorFieldsOfHeadersOfMessage;
